version: "3.8"

services:
  farm-robot-sim:
    image: tb3_nav2_slam:humble
    container_name: farm_robot_sim
    stdin_open: true
    tty: true

    network_mode: host

    environment:
      - DISPLAY=${DISPLAY}

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/farm-robot-navigation/worlds:/root/ws/src/turtlebot3_simulations/turtlebot3_gazebo/worlds
      - ~/farm-robot-navigation/maps:/root/ws/maps

    command: bash
